# address 监听地址，默认'127.0.0.1:14000'
address: '127.0.0.1:14000'
# contact_bilibili 允许访问Bilibili服务器，获取主播头像，下播时检查直播间封禁状态。
contact_bilibili: true
debug: false
Bark:
#    需要多个服务器可多复制几遍
#  - url: 推送服务器地址，默认"https://api.day.app/"
#    secrets: 你的推送密钥，格式为 "ABcDeFg1hIjkLmNOPQrstu"
  - url: "https://api.day.app/"
    secrets: ""

WXWorkApp:
#  - corpId: "ww123456789a01b2c3"
#    appSecret: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFG"
#    agentId: "1000002"
#    to_user: "@all"
  - corpId: ""
    appSecret: ""
    agentId: ""
    to_user: "@all"

BililiveRecoder:
  # enable 是否启用该服务
  enable: true
  # path 该服务的访问路径
  path: '/bililiverecoder'
  # events 该服务监听的事件，事件种类见 https://rec.danmuji.org/reference/webhook/#webhook-v2
  events:
    SessionStarted:
      # care 是否在控制台提示收到了该事件
      care: false
      # notify 是否推送该事件
      notify: false
      # have_command 是否执行命令
      have_command: false
      # exec_command 执行的命令
      exec_command: ""
    FileOpening:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    FileClosed:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    SessionEnded:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    StreamStarted:
      care: true
      notify: true
      have_command: false
      exec_command: ""
    StreamEnded:
      care: true
      notify: true
      have_command: false
      exec_command: ""
Blrec:
  enable: true
  path: '/blrec'
  # 事件种类及可提取的信息见 https://github.com/acgnhiki/blrec/wiki/Webhook
  events:
    LiveBeganEvent:
      care: true
      notify: true
      have_command: false
      exec_command: ""
    LiveEndedEvent:
      care: true
      notify: true
      have_command: false
      exec_command: ""
    RoomChangeEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    RecordingStartedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    RecordingFinishedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    RecordingCancelledEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    VideoFileCreatedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    VideoFileCompletedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    DanmakuFileCreatedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    DanmakuFileCompletedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    RawDanmakuFileCreatedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    RawDanmakuFileCompletedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    VideoPostprocessingCompletedEvent:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    SpaceNoEnoughEvent:
      care: true
      notify: true
      have_command: false
      exec_command: ""
    Error:
      care: true
      notify: true
      have_command: false
      exec_command: ""
DDTV3:
  enable: true
  path: "/ddtv"
  # 事件种类见 https://ddtv.pro/AdvancedFeatures/Webhook.html#%E4%BA%8B%E4%BB%B6%E7%B1%BB%E5%9E%8B
  events:
    StartLive:
      care: true
      notify: true
      have_command: false
      exec_command: ""
    StopLive:
      care: true
      notify: false
      have_command: false
      exec_command: ""
    StartRec:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    RecComplete:
      care: true
      notify: false
      have_command: false
      exec_command: ""
    CancelRec:
      care: true
      notify: false
      have_command: false
      exec_command: ""
    TranscodingComplete:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    SaveDanmuComplete:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    SaveSCComplete:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    SaveGiftComplete:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    SaveGuardComplete:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    RunShellComplete:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    DownloadEndMissionSuccess:
      care: true
      notify: true
      have_command: false
      exec_command: ""
    SpaceIsInsufficientWarn:
      care: true
      notify: false
      have_command: false
      exec_command: ""
    LoginFailure:
      care: true
      notify: false
      have_command: false
      exec_command: ""
    LoginWillExpireSoon:
      care: true
      notify: false
      have_command: false
      exec_command: ""
    UpdateAvailable:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    ShellExecutionComplete:
      care: false
      notify: false
      have_command: false
      exec_command: ""
    WarnedByAdmin:
      care: true
      notify: true
      have_command: false
      exec_command: ""
    LiveCutOff:
      care: true
      notify: true
      have_command: false
      exec_command: ""
    RoomLocked:
      care: true
      notify: true
      have_command: false
      exec_command: ""
